repos:
  - repo: https://github.com/psf/black
    rev: "23.9.1"  # Latest valid tag for Black
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1"
    hooks:
      - id: isort
